CREATE TABLE market
(
    id                  INT,
    product_name        VARCHAR(255),
    product_description TEXT,
    price               DECIMAL(10, 2),
    quantity            INT,
    is_available        BOOLEAN,
    created_at          TIMESTAMP,
    expiration_date     DATE,
    product_code        CHAR(10),
    weight              FLOAT,
    discount            DOUBLE,
    product_rating      SMALLINT,
    color               ENUM ('black', 'purple', 'green'),
    total_sold          BIGINT
);
INSERT INTO market (id,
                    product_name,
                    product_description,
                    price,
                    quantity,
                    is_available,
                    created_at,
                    expiration_date,
                    product_code,
                    weight,
                    discount,
                    product_rating,
                    color,
                    total_sold)
VALUES (1,
        'Iphone 16',
        'The iPhone 16 and iPhone 16 Plus retain their screen sizes of 6.1 inches and 6.7 inches, respectively. They feature a bezel-less, full-edge screen design with no visible borders.',
        799,
        320,
        TRUE,
        '2024-10-22 10:40:03',
        '2025-10-25',
        'IP16PL1234',
        0.174,
        10.5,
        5,
        'black',
        120000);
