CREATE TABLE market
(
    id                  SMALLINT,
    product_name        VARCHAR(255),
    product_description TEXT,
    price               DECIMAL(10, 2),
    quantity            MEDIUMINT,
    is_available        BOOLEAN,
    created_at          TIMESTAMP,
    expiration_date     DATE,
    product_code        CHAR(10),
    weight              FLOAT,
    discount            DOUBLE,
    product_rating      INTEGER,
    color               ENUM ('black', 'purple', 'green'),
    total_sold          BIGINT,
    product_image       BLOB,
    product_uuid        CHAR(36),
    available_colors    SET ('black', 'purple', 'green', 'blue', 'red'),
    production_year     YEAR,
    production_time     TIME,
    small_flag          TINYINT,
    additional_info     MEDIUMTEXT,
    extended_info       LONGTEXT,
    last_update         DATETIME

);

INSERT INTO market (id,
                    product_name,
                    product_description,
                    price,
                    quantity,
                    is_available,
                    created_at,
                    expiration_date,
                    product_code,
                    weight,
                    discount,
                    product_rating,
                    color,
                    total_sold,
                    product_image,
                    product_uuid,
                    available_colors,
                    production_year,
                    production_time,
                    small_flag,
                    additional_info,
                    extended_info,
                    last_update)
VALUES (1,
        'Iphone 16',
        'The iPhone 16 and iPhone 16 Plus retain their screen sizes of 6.1 inches and 6.7 inches, respectively. They feature a bezel-less, full-edge screen design with no visible borders.',
        799,
        320,
        TRUE,
        '2024-10-22 10:40:03',
        '2025-10-25',
        'IP16PL1234',
        0.174,
        10.5,
        5,
        'black',
        120000,
        NULL,
        '550e8400-e29b-41d4-a716-446655440000',
        'black, blue',
        2024,
        '15:20:32',
        1,
        'Limited edition product with special packaging.',
        'This product includes a warranty for 1 year, with a possibility of extension up to 3 years. It also supports fast charging and wireless charging. Full technical specifications are available on the official website.',
        '2024-10-22 12:30:45');

