CREATE TABLE market
(
    id                  INT,
    product_name        VARCHAR(255),
    product_description TEXT,
    price               NUMERIC(10, 2),
    quantity            INTEGER,
    is_available        BOOLEAN,
    created_at          TIMESTAMP,
    expiration_date     DATE,
    product_code        CHAR(8),
    weight              REAL,
    product_rating      SMALLINT,
    product_image       bytea,
    product_uuid        uuid,
    available_color     TEXT[],
    discount            NUMERIC(5, 2),
    product_year        INTEGER,
    warranty_period     SMALLINT,
    large_stock         BIGINT,
    precision_value     DOUBLE PRECISION,
    currency_value      MONEY,
    last_ordered_at     TIMESTAMPTZ,
    opening_time        TIME,
    closing_time        TIME WITH TIME ZONE,
    shipping_interval   INTERVAL,
    allowed_ips         CIDR,
    customer_ip         INET,
    device_mac          MACADDR
);
INSERT INTO market (id,
                    product_name,
                    product_description,
                    price,
                    quantity,
                    is_available,
                    created_at,
                    expiration_date,
                    product_code,
                    weight,
                    product_rating,
                    product_image,
                    product_uuid,
                    available_color,
                    discount,
                    product_year,
                    warranty_period,
                    large_stock,
                    precision_value,
                    currency_value,
                    last_ordered_at,
                    opening_time,
                    closing_time,
                    shipping_interval,
                    allowed_ips,
                    customer_ip,
                    device_mac)

VALUES (1,
        'iPhone 16',
        'The iPhone 16 features a bezel-less, full-edge screen with no visible borders, 6.1 inches in size.',
        799.99,
        500,
        TRUE,
        '2024-10-22 11:23:32',
        '2025-10-25',
        'IP16PL12',
        0.176,
        5,
        NULL,
        '550e8400-e29b-41d4-a716-446655440000',
        '{"black", "blue"}',
        10.50,
        2024,
        12,
        10000,
        0.178,
        799.99,
        '2024-10-21 14:32:00+00',
        '09:00:00',
        '18:00:00+00',
        '2 days',
        '192.168.0.0/24',
        '192.168.0.10',
        '00:1B:44:11:3A:B7'
       );